channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.8.0
  - pip
  - python=2.7
  - pip:
    - grpcio==1.27.1
    - h5py==2.10.0
    - matplotlib==2.2.5
    - MedPy==0.3.0
    - numpy==1.12.0
    - opencv-python==4.2.0.32
    - tensorflow==1.10
